# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

### Plugins ###
plugins:
  - jemoji
  - jekyll-feed

### Site Settings ###
locale                   : "en-US"
title                    : "Sam Loves Coffee ðŸ‘±â€â™‚ï¸ðŸ¤â˜•"
description         : >-
                      I turn data into information,
                      make that information actionable,
                      and make those actions the right ones.
url                      : https://samuelcochrane.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
imgurl                   : https://samuelcochrane.github.io/assets/images
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"

teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200

nav_exclude:
  - pages/tags.html
  - pages/404.html
  - pages/index.html
  - pages/projects.html



### Author Info ###
author:
  name             : Samuel Cochrane
  image           : /assets/images/bio-photo.jpg
  bio              : "Seattle-area information professional, bean-juice connoisseur."
  location         : Redmond, WA
  email            :
  uri              :
  home             : # null (default), "absolute or relative url to link to author home"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : samuelcochrane
  gitlab           :
  google_plus      :
  keybase          :
  instagram        : #NotAMaleModel
  lastfm           :
  linkedin         : sam-cochrane-aaa325110 # "john-doe-12345678" (the last part of your profile url, e.g. https://www.linkedin.com/in/john-doe-12345678)
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          : # "https://youtube.com/c/MichaelRoseDesign"

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
# Reading Files
include:
  - .htaccess
  - _pages
### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

#RSS feed at /feed.xml
feed:
  posts_limit: 20